/**
 * 代碼集目錄(catalog)與 alias 預設組
 *
 * - LAB_CATALOG:一對一常用檢驗項目,使用者從編輯器篩選加入(pilot 不開放自由輸入代碼)。
 *   來源:KMUH 公開檢驗目錄(www.kmuh.org.tw/Web/KMULab,2026-07-07 快照),
 *   以 order_code 去重(同檢驗跨科/檢體變體只取一,標籤取最簡短名稱)+
 *   專案手挑常用碼(標籤優先)。公開標準醫令碼,非個資。
 *   再生方式見 docs/superpowers/plans/2026-07-07-codeset-pilot.md Task 1;手動加行亦可。
 * - alias 預設組:專案維護的已知一對多代碼組合(2026-07-07 測資查證:
 *   CRP/hs-CRP 與 Cr/CCr 為同碼多 itemName 不需 alias;尿蛋白跨碼但有
 *   itemName 歧義留待後續;初版僅 CBC)。
 */
export const LAB_CATALOG = [
  { code: '06003C', label: 'Total Protein(Urine,24hr)' },
  { code: '06012C', label: 'Complete Urine Routine Examiation' },
  { code: '06013C', label: 'Urine biochemistry examination' },
  { code: '06503B', label: 'Urine osmolarity' },
  { code: '06505C', label: 'Pregnancy test' },
  { code: '06510C', label: 'Paraquat' },
  { code: '07001C', label: 'Stool occult blood' },
  { code: '07004C', label: 'Starch stain' },
  { code: '07005C', label: 'Neutral fat stain' },
  { code: '07006C', label: 'Fatty acid stain' },
  { code: '07009C', label: 'Stool routine examination' },
  { code: '07011C', label: 'Stain for Pneumocystis carinii' },
  { code: '07012C', label: 'Concentration method of parasite (含Amoeba)' },
  { code: '07016C', label: 'Perianal swab' },
  { code: '08005C', label: 'ESR' },
  { code: '08007C', label: 'smear for blood parasite (malaria or filaria)' },
  { code: '08008C', label: 'Reticulocyte' },
  { code: '08010C', label: 'Eosinophil count' },
  { code: '08013C', label: 'WBC classification' },
  { code: '08019C', label: 'Bleeding time(Ivy method)' },
  { code: '08024B', label: 'Fibrinogen' },
  { code: '08025B', label: 'Thrombin Time' },
  { code: '08026C', label: 'Prothrombin time' },
  { code: '08030C', label: 'Hb Variant' },
  { code: '08036C', label: 'APTT (activated partial thromboplastin time)' },
  { code: '08038B', label: 'FDP ( Fibrin degradation product)－ quantitative' },
  { code: '08042C', label: 'Iron stain(請填寫 aspiration site)' },
  { code: '08043C', label: 'Sudan black B stain(請填寫 aspiration site)' },
  { code: '08044B', label: 'Leukocyte alkaline phosphatase stain' },
  { code: '08046B', label: 'Fibrin split product (3\'P)' },
  { code: '08047B', label: 'Peroxidase stain(請填寫 aspiration site)' },
  { code: '08048B', label: 'Naphthol AS-D Chloroacetatse stain(請填寫 aspiration site)' },
  { code: '08049B', label: 'Non Specific Esterase Stain(請填寫 aspiration site)' },
  { code: '08051B', label: 'Periodic acid-schiff stain(請填寫 aspiration site)' },
  { code: '08057B', label: 'Factor Ⅱ assay' },
  { code: '08058B', label: 'Factor Ⅴ assay' },
  { code: '08059B', label: 'Factor Ⅶ assay' },
  { code: '08060B', label: 'Clotting factor VIII' },
  { code: '08061B', label: 'Clotting factor IX' },
  { code: '08062B', label: 'Factor Ⅹ assay' },
  { code: '08067B', label: 'Factor Ⅷ inhibitor test' },
  { code: '08069B', label: '血小板凝集試驗' },
  { code: '08072B', label: 'Anti-Thrombin - III Assay' },
  { code: '08075C', label: 'Blood osmolarity' },
  { code: '08077B', label: 'Protein C' },
  { code: '08078B', label: 'α-2-Antiplasmin' },
  { code: '08079B', label: 'D-Dimer' },
  { code: '08080B', label: 'Clotting factor XI' },
  { code: '08081B', label: 'Factor XⅡ assay' },
  { code: '08092B', label: 'Mixed APTT' },
  { code: '08103B', label: 'Factor 9 inhibitor' },
  { code: '08111B', label: 'vWF activity (GPIbM)' },
  { code: '08118B', label: 'von Willebrand Factor' },
  { code: '08122B', label: 'Protein S' },
  { code: '08126B', label: 'Lupus anticoaqulation' },
  { code: '08130C', label: 'Bone-alkaline phosphatase' },
  { code: '08133B', label: 'Cystatin C' },
  { code: '09003C', label: 'UN(U)' },
  { code: '09010C', label: 'T4' },
  { code: '09016C', label: 'Cr(Urine)' },
  { code: '09017C', label: 'Amylase(B)' },
  { code: '09020C', label: 'Fe' },
  { code: '09023C', label: 'Cl' },
  { code: '09032C', label: 'CPK' },
  { code: '09033C', label: 'LDH' },
  { code: '09035C', label: 'TIBC' },
  { code: '09037C', label: 'Ammonia' },
  { code: '09041B', label: 'Blood PH/gas Analysis' },
  { code: '09046B', label: 'Mg' },
  { code: '09047B', label: 'Copper(Cu)' },
  { code: '09049B', label: 'Lead(Pb) (WB)' },
  { code: '09051C', label: 'G-6-P-D (Glucose-6-phosphate-dehydrogenase)' },
  { code: '09052B', label: 'Vannillylmandelic Acid (VMA)' },
  { code: '09059B', label: 'Lactate' },
  { code: '09061B', label: 'CK isoenzymes' },
  { code: '09062B', label: 'LD isoenzymes (請加開一般生化的LDH)' },
  { code: '09064C', label: 'Lipase' },
  { code: '09065B', label: 'Protein EP' },
  { code: '09066B', label: 'Lipoprotein Ep' },
  { code: '09071C', label: 'CK-MB' },
  { code: '09078B', label: 'Stone analysis' },
  { code: '09083B', label: 'Cholinesterase' },
  { code: '09093B', label: 'ICG(Indocyanine green)' },
  { code: '09099C', label: 'Troponin I' },
  { code: '09102B', label: 'ADA' },
  { code: '09105C', label: 'Progesteron' },
  { code: '09106C', label: 'Free T4' },
  { code: '09112C', label: 'TSH' },
  { code: '09117C', label: 'T3' },
  { code: '09122C', label: 'iPTH' },
  { code: '09125C', label: 'FSH' },
  { code: '09126C', label: 'LH' },
  { code: '09127C', label: 'Estradiol(E2)' },
  { code: '09129C', label: 'Vitamin B12' },
  { code: '09130C', label: 'Folic acid' },
  { code: '09134C', label: 'Stool Occult Blood Immunity Quantitative Examination' },
  { code: '09136B', label: 'Carbohydrate-deficient transferrin' },
  { code: '09137B', label: 'Blood ketone' },
  { code: '09140C', label: 'Glucose(Random)' },
  { code: '10002B', label: 'Aluminum(Al)' },
  { code: '10003B', label: 'Arsenic(As)' },
  { code: '10005B', label: 'Cadmicum(Cd)' },
  { code: '10007B', label: 'Chromiom (Cr)' },
  { code: '10008B', label: 'Hg (WB)' },
  { code: '10009B', label: 'Manganese(Mn)' },
  { code: '10010B', label: 'Nickel (Ni)' },
  { code: '10012B', label: 'Zinc(Zn)' },
  { code: '10501C', label: 'Carbamazepine' },
  { code: '10502B', label: 'Diphenylhydantoin' },
  { code: '10504B', label: 'Methotrexate' },
  { code: '10509B', label: 'Theophylline(THE)' },
  { code: '10510C', label: 'Valproic acid' },
  { code: '10511C', label: 'Digoxin' },
  { code: '10512B', label: 'Amikacin' },
  { code: '10518B', label: 'Gentamicin' },
  { code: '10520C', label: 'Li' },
  { code: '10522B', label: 'Cyclosporin' },
  { code: '10527B', label: 'Benzodiazepine (定性)' },
  { code: '10531B', label: 'Therapeutic drug monitoring-vancomycin' },
  { code: '10536B', label: 'FK506' },
  { code: '10537C', label: 'Sirolimus 全血濃度測定' },
  { code: '10802B', label: 'Phenobarbital' },
  { code: '10803B', label: 'Acetaminophen' },
  { code: '10804B', label: 'CO Analysis' },
  { code: '10805B', label: 'Cyanide Analysis' },
  { code: '10806B', label: 'Methanol Analysis' },
  { code: '10807B', label: 'Ethanol(quantitative)' },
  { code: '10810B', label: 'Amphetamine Screening test' },
  { code: '10811B', label: 'Morphine Screening test' },
  { code: '10812B', label: 'Cocaine Screening test' },
  { code: '10813B', label: 'Cannabinoid Screening test' },
  { code: '10814B', label: '天使塵(PCP)篩檢測試' },
  { code: '11001C', label: 'ABO blood grouping' },
  { code: '11002C', label: 'Cross matching test' },
  { code: '11003C', label: 'Rh(D) typing' },
  { code: '11004C', label: 'Antibody screening 不規則抗體篩檢' },
  { code: '11005B', label: 'Antibody identification' },
  { code: '11009B', label: 'Rh phenotyping ________' },
  { code: '11010B', label: 'Special blood group' },
  { code: '11011B', label: 'Investigation transfusion reaction' },
  { code: '12001C', label: 'STS (RPR test)' },
  { code: '12002B', label: 'Widal test' },
  { code: '12004C', label: 'ASLO' },
  { code: '12007C', label: 'AFP' },
  { code: '12008B', label: 'Cold agglutinin titer' },
  { code: '12011C', label: 'Rheumatoid Factor(RA factor)' },
  { code: '12015C', label: 'CRP' },
  { code: '12018C', label: 'Treponemal test (CIA)' },
  { code: '12019B', label: 'FTA-ABS( Serum )' },
  { code: '12020C', label: 'Mycoplasma IgG' },
  { code: '12021C', label: 'CEA' },
  { code: '12022C', label: 'B-HCG' },
  { code: '12025B', label: 'IgG(other)' },
  { code: '12027B', label: 'Immunoglobulin A (IgA)' },
  { code: '12029B', label: 'Immunoglobulin M (IgM)' },
  { code: '12031C', label: 'Immunoglobulin E (IgE)' },
  { code: '12034B', label: 'C3' },
  { code: '12038B', label: 'C4' },
  { code: '12041B', label: 'α1-Antitrypsin' },
  { code: '12046B', label: 'Haptoglobin' },
  { code: '12048C', label: 'Transferrin' },
  { code: '12050B', label: 'Ceruloplasmin' },
  { code: '12052B', label: 'β2-Microglobulin' },
  { code: '12053C', label: 'Antinuclear antibody' },
  { code: '12058B', label: 'Anti-Parietal cell antibody (APCA)' },
  { code: '12060C', label: 'Anti-dsDNA antibody' },
  { code: '12061B', label: 'Myoglobin' },
  { code: '12062B', label: 'Cryoglobulin' },
  { code: '12063B', label: 'Anti-ENA screen' },
  { code: '12064B', label: 'Anti-Ro52 antibody' },
  { code: '12069B', label: 'Cryptococcus antigen (Serum)' },
  { code: '12073C', label: 'Lymphocyte surface marker－infections disease' },
  { code: '12074B', label: 'Lymphocyte surface marker－ Immunological disease' },
  { code: '12075B', label: 'PNH immunophenotyping' },
  { code: '12077C', label: 'CA-125' },
  { code: '12078C', label: 'CA153' },
  { code: '12079C', label: 'CA199' },
  { code: '12080B', label: 'SCC' },
  { code: '12081C', label: 'PSA' },
  { code: '12086C', label: 'HLA-B27' },
  { code: '12087B', label: 'HLA type-ABC (人類白血球抗原分型 HLA-ABC)' },
  { code: '12088B', label: 'HLA type-DR,DQ (人類白血球抗原分型 HLA-DR,DQ )' },
  { code: '12090B', label: 'Lymphocytotoxic test' },
  { code: '12097B', label: 'Direct Coombs test(Direct Antiglobulin test,DAT)' },
  { code: '12098B', label: 'Indirect Coombs test(Indirect Antiglobulin test,IAT)' },
  { code: '12099B', label: 'Coombs IgG monospecific test(DAT(+)時,進一步作此檢驗)' },
  { code: '12100B', label: 'Coombs C3d monospecific test(DAT(+)時,進一步作此檢驗)' },
  { code: '12103B', label: 'Immuno fixation electrophoresis ( Serum )' },
  { code: '12104B', label: 'CH50 (CAE)' },
  { code: '12107C', label: 'Chlamydia trachomatis IgM' },
  { code: '12108B', label: 'C1q Circulating Immune Complex' },
  { code: '12109B', label: 'Anti-HTLV-Ⅰ/Anti-ATLA Ab' },
  { code: '12110B', label: 'Prealbumin' },
  { code: '12112B', label: 'Albumin (CSF)' },
  { code: '12113B', label: 'Apo B' },
  { code: '12114B', label: 'Apo A' },
  { code: '12116C', label: 'Ferritin' },
  { code: '12118B', label: 'Legionella Ab FA test ( Serum )' },
  { code: '12125C', label: 'Streptococcal group B antigen' },
  { code: '12126B', label: 'Pneumococcal antigen' },
  { code: '12127B', label: 'H. influenzal type B antigen' },
  { code: '12128B', label: 'Meningococcal antigen' },
  { code: '12133B', label: 'Anti-β2 glycoprotein 1 IgM' },
  { code: '12137B', label: 'Anti-Mi 2 antibody' },
  { code: '12138B', label: 'Anti-Glomerular basement membrane antibody' },
  { code: '12149B', label: 'IGG4 level' },
  { code: '12151C', label: 'Homocysteine' },
  { code: '12154B', label: 'Anti Jo-1 antibody' },
  { code: '12156B', label: 'Anti-Ribsomal P antibody' },
  { code: '12157B', label: 'Immuno Fixation electrophoresis (C.S.F)' },
  { code: '12159B', label: 'Immuno fixation electrophoresis(Urine)' },
  { code: '12160B', label: 'Free Kappa,Lambda' },
  { code: '12164B', label: 'Lipoprotein a' },
  { code: '12165C', label: 'Streptococcal group A antigen' },
  { code: '12170B', label: 'A. niger IgG' },
  { code: '12171B', label: 'Anti-PR3 antibody' },
  { code: '12172C', label: 'Pneumococcus Ag (urine)' },
  { code: '12173B', label: 'Anti-RNP/Sm antibody' },
  { code: '12174B', label: 'Anti-Scl-70 antibody' },
  { code: '12179C', label: 'Aspergillus Ag' },
  { code: '12182C', label: '困難梭狀桿菌PCR檢驗' },
  { code: '12183C', label: 'EV PCR' },
  { code: '12184C', label: 'BK病毒負荷量' },
  { code: '12188C', label: 'BCR-ABL gene' },
  { code: '12191C', label: 'Leginella pneumophila Ag( urine)' },
  { code: '12193C', label: 'N-terminal pro-brain natriuretic peptide(NT-pro BNP)' },
  { code: '12194B', label: 'Tandem Mass Analysis of Metabolites' },
  { code: '12196B', label: 'HLA-B 1502 gene typing' },
  { code: '12198C', label: 'Free Prostatic Specific Antigen Test' },
  { code: '12201B', label: 'Anti-CCP antibody' },
  { code: '12204B', label: 'Plasma Cell Disorder Panel (MRD)-BM' },
  { code: '12205B', label: 'Plasma Cell Disorder Panel (fresh)' },
  { code: '12206B', label: 'B-ALL Panel (MRD)-BM' },
  { code: '12209B', label: 'Tryptase Test' },
  { code: '12210B', label: 'Aquaporin-4 Antibody' },
  { code: '12211B', label: 'Protein Induced by Vitamin K Absence or Antagonist-II' },
  { code: '12212B', label: 'FilmArray Meningitis/Encephalitis Panel' },
  { code: '12213B', label: 'HLA-B* 5801基因檢測' },
  { code: '12215C', label: '新型冠狀病毒核糖核酸定性擴增試驗' },
  { code: '12217B', label: 'BCR-ABL 基因定量檢查 (健保)' },
  { code: '13002B', label: 'Amoebiasis test' },
  { code: '13005B', label: 'Chlamydia DNA (qualitative)' },
  { code: '13006C', label: 'India ink stain' },
  { code: '13007C', label: 'GBS culture (含藥敏申請)' },
  { code: '13030B', label: 'Special culture for Helicobacter pylori(含 3 種藥敏)' },
  { code: '14001B', label: 'Virus isolation and identification-stool' },
  { code: '14002B', label: 'ADV IgM' },
  { code: '14004B', label: 'CMV IgG' },
  { code: '14009C', label: 'Mumps IgG' },
  { code: '14010B', label: 'RSV' },
  { code: '14013B', label: 'VZV IgM' },
  { code: '14026C', label: 'Rotavirus (請用無菌空容器收集STOOL)' },
  { code: '14032C', label: 'HBsAg' },
  { code: '14033C', label: 'HBs Ab' },
  { code: '14035C', label: 'HBe Ag' },
  { code: '14036C', label: 'HBe Ab' },
  { code: '14037C', label: 'HBc IgG' },
  { code: '14038C', label: 'HBc IgM' },
  { code: '14039C', label: 'Hepatitis A virus IgM' },
  { code: '14040C', label: 'HAVAB-G' },
  { code: '14042B', label: 'Toxoplasma IgG' },
  { code: '14044B', label: 'Rubella virus IgG' },
  { code: '14045B', label: '★Rubella virus IgM' },
  { code: '14046B', label: 'EBV-VCA IgG' },
  { code: '14047B', label: 'EBNA Ab' },
  { code: '14048B', label: 'CMV IgM' },
  { code: '14051C', label: 'Anti-HCV Ab' },
  { code: '14052B', label: 'Herpes Simplex Virus Type 1 IgM' },
  { code: '14058C', label: 'RSV Ag Rapid Test' },
  { code: '14064C', label: 'ADV' },
  { code: '14068B', label: 'Varicella Zoster Virus IgG' },
  { code: '14069B', label: 'Herpes Simplex Virus Type 1 IgG' },
  { code: '14070B', label: 'Measles IgG' },
  { code: '14071B', label: 'Toxoplasma IgM' },
  { code: '14074C', label: 'HIV 病毒負荷量(RT-PCR)(Plasma)' },
  { code: '14082C', label: 'HIV Ag/Ab Combo Test (ELISA)' },
  { code: '14083C', label: 'HIV色層免疫分析法' },
  { code: '14084C', label: '新型冠狀病毒抗原檢測' },
  { code: '16001C', label: 'Semen examination' },
  { code: '16002C', label: 'Ascites analysis' },
  { code: '16003C', label: 'Pleural effusion analysis' },
  { code: '16006C', label: 'CSF analysis' },
  { code: '16007C', label: 'Pus or discharge analysis' },
  { code: '16008C', label: 'Synovial fluid analysis' },
  { code: '16010C', label: 'Analysis of total cell count and differentiation in BAL fluid' },
  { code: '16013C', label: 'Polarized microscopic examinations of synovial fluid' },
  { code: '24007B', label: 'Ca++' },
  { code: '24009C', label: 'GTT' },
  { code: '25007B', label: 'Bone Marrow High resolution Chromosome analysis' },
  { code: '25021B', label: 'Chromosome examination-Blood' },
  { code: '30013B', label: 'C1 esterase inhibitor' },
  { code: '30018B', label: 'CTD Ab screen' },
  { code: '30019B', label: 'Anti-Histone Antibody' },
  { code: '30020B', label: 'Anti-cardiolopin antibody IgG' },
  { code: '30021C', label: 'Phadiatop' },
  { code: '30022C', label: 'BioIC過敏原晶片' },
  { code: '30023B', label: 'ECP檢測' },
  { code: '30027B', label: 'Anti-phosphatidylserine and prothrombin complex antibody IgG' },
  { code: '30028B', label: 'Anti-cardiolopin antibody IgM' },
  { code: '30029B', label: 'Anti-phosphatidylserine and prothrombin complex antibody IgM' },
  { code: '30108B', label: 'KIT and PDGFRA mutation testing' },
  { code: '30522C', label: 'Helicobacter pylori stool antigen(HpSA)Test' },
];

export const IMAGE_CATALOG = [
  { code: '32011C', label: '脊椎X光' },
  { code: '32006C', label: 'KUB' },
  { code: '19005C', label: '其他超音波(19005C)' },
  { code: '18007C', label: '心臟都卜勒血流圖' },
  { code: '32018C', label: '下肢骨關節X光' },
];

export const LAB_ALIAS_PRESETS = [
  { id: 'alias:cbc', label: 'CBC', codes: ['08011C', '08003C'] },
];

export const IMAGE_ALIAS_PRESETS = [];
